[project]
name = "llm-search"
version = "0.1.0"
description = ""
authors = [
    {name = "Daisy Lin",email = "daisy@acts.net"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
